version: "3.8"

services:
  member-session-redis-clustering:
    container_name: member-session-redis-clustering
    build:
      context: ./server/redis
      dockerfile: Dockerfile
    platform: linux/amd64
    command: >
      127.0.0.1:6379 127.0.0.1:6380 127.0.0.1:6381
      127.0.0.1:6389 127.0.0.1:6390 127.0.0.1:6391
    depends_on:
      - member-session-redis-master-01
      - member-session-redis-master-02
      - member-session-redis-master-03
      - member-session-redis-slave-01
      - member-session-redis-slave-02
      - member-session-redis-slave-03
    network_mode: host

  member-session-redis-master-01:
    container_name: member-session-redis-master-01
    image: amd64/redis:6.2-alpine
    platform: linux/amd64
    ports:
      - target: 6379
        published: 6379
      - target: 16379
        published: 16379
    volumes:
      - ./server/redis/redis-master-01.conf:/usr/local/etc/redis/redis.conf
    command:
      - /usr/local/etc/redis/redis.conf
    network_mode: host

  member-session-redis-master-02:
    container_name: member-session-redis-master-02
    image: amd64/redis:6.2-alpine
    platform: linux/amd64
    ports:
      - target: 6380
        published: 6380
      - target: 16380
        published: 16380
    volumes:
      - ./server/redis/redis-master-02.conf:/usr/local/etc/redis/redis.conf
    command:
      - /usr/local/etc/redis/redis.conf
    network_mode: host

  member-session-redis-master-03:
    container_name: member-session-redis-master-03
    image: amd64/redis:6.2-alpine
    platform: linux/amd64
    ports:
      - target: 6381
        published: 6381
      - target: 16381
        published: 16381
    volumes:
      - ./server/redis/redis-master-03.conf:/usr/local/etc/redis/redis.conf
    command:
      - /usr/local/etc/redis/redis.conf
    network_mode: host

  member-session-redis-slave-01:
    container_name: member-session-redis-slave-01
    image: amd64/redis:6.2-alpine
    platform: linux/amd64
    ports:
      - target: 6389
        published: 6389
      - target: 16389
        published: 16389
    volumes:
      - ./server/redis/redis-slave-01.conf:/usr/local/etc/redis/redis.conf
    command:
      - /usr/local/etc/redis/redis.conf
    network_mode: host

  member-session-redis-slave-02:
    container_name: member-session-redis-slave-02
    image: amd64/redis:6.2-alpine
    platform: linux/amd64
    ports:
      - target: 6390
        published: 6390
      - target: 16390
        published: 16390
    volumes:
      - ./server/redis/redis-slave-02.conf:/usr/local/etc/redis/redis.conf
    command:
      - /usr/local/etc/redis/redis.conf
    network_mode: host

  member-session-redis-slave-03:
    container_name: member-session-redis-slave-03
    image: amd64/redis:6.2-alpine
    platform: linux/amd64
    ports:
      - target: 6391
        published: 6391
      - target: 16391
        published: 16391
    volumes:
      - ./server/redis/redis-slave-03.conf:/usr/local/etc/redis/redis.conf
    command:
      - /usr/local/etc/redis/redis.conf
    network_mode: host

