spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/deliveryplatform
    username: root
    password: root

  flyway:
    enabled: false

  jpa:
    database: mysql
    open-in-view: false
    properties:
      hibernate.default_batch_fetch_size: 1000

server:
  port: 8080

auth:
  token:
    access-token-expired-time-secs: 1800

async-thread-pool:
  core-pool-size: 3
  max-pool-size: 20
  queue_capacity: 15
  thread_name_prefix: ASYNC_THREAD-
