spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13306/deliveryplatform
    username: root
    password: root

  flyway:
    url: jdbc:mysql://localhost:13306/deliveryplatform
    user: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    enabled: true
    baseline-on-migrate: true
    locations: db/migration

  jpa:
    database: mysql
    show-sql: true
    open-in-view: false

  redis:
    cluster:
      nodes:
        - localhost:6379
        - localhost:6380
        - localhost:6381
        - localhost:6389
        - localhost:6390
        - localhost:6391

  boot:
    admin:
      client:
        url: http://localhost:18090

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 18080

auth:
  token:
    access-token-expired-time-millis: 1800000

async-thread-pool:
  core-pool-size: 3
  max-pool-size: 20
  queue_capacity: 15
  thread_name_prefix: ASYNC_THREAD-
