spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/deliveryplatform
    username: root
    password: root

  jpa:
    database: mysql

server:
  port: 8080
